// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AttachmentDetail: typeof import('./components/AttachmentDetail.vue')['default']
    AuditSelect: typeof import('./components/AuditStatus/AuditSelect.vue')['default']
    AuditTag: typeof import('./components/AuditStatus/AuditTag.vue')['default']
    BreadCrumb: typeof import('./components/BreadCrumb.vue')['default']
    DepartmentSelect: typeof import('./components/department/DepartmentSelect.vue')['default']
    Header: typeof import('./components/Layout/header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Menu: typeof import('./components/Layout/menu.vue')['default']
    Nav: typeof import('./components/Layout/compoents/nav.vue')['default']
    PermitSelect: typeof import('./components/permit/PermitSelect.vue')['default']
    RoleSelect: typeof import('./components/role/RoleSelect.vue')['default']
    StageSelect: typeof import('./components/stage/StageSelect.vue')['default']
  }
}

export { }
